apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-api
  labels:
    app: clinic-api
    domain: health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-api
  template:
    metadata:
      labels:
        app: clinic-api
        domain: health
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: app
          image: clinic-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
