input {
  beats { port => 5044 }
  http { port => 8080 }
}
filter {
  json { source => "message" skip_on_invalid_json => true }
  mutate { add_field => { "platform" => "synthetic-banking" } }
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "banking-services-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
